[package]
name = "glyphshift-adapter-raylib-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
glyphshift-adapter-native-abi = { path = "../glyphshift-adapter-native-abi" }
glyphshift-adapter-raylib = { path = "../glyphshift-adapter-raylib" }
retour = "0.3"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
]

[lints.rust]
unsafe_code = "allow"
