/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptureView: typeof import('./src/components/CaptureView.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DictionaryLibrary: typeof import('./src/components/DictionaryLibrary.vue')['default']
    DictionaryProof: typeof import('./src/components/DictionaryProof.vue')['default']
    HelpView: typeof import('./src/components/HelpView.vue')['default']
    ManagementDetailHeader: typeof import('./src/components/ManagementDetailHeader.vue')['default']
    ManagementFormModal: typeof import('./src/components/ManagementFormModal.vue')['default']
    ManagementFormRow: typeof import('./src/components/ManagementFormRow.vue')['default']
    ManagementFormSection: typeof import('./src/components/ManagementFormSection.vue')['default']
    ManagementPageHeader: typeof import('./src/components/ManagementPageHeader.vue')['default']
    ManagementTableFrame: typeof import('./src/components/ManagementTableFrame.vue')['default']
    ManagementWorkspaceSurface: typeof import('./src/components/ManagementWorkspaceSurface.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuntimeDiagnosticsModal: typeof import('./src/components/RuntimeDiagnosticsModal.vue')['default']
    SettingsView: typeof import('./src/components/SettingsView.vue')['default']
    SoftwareTable: typeof import('./src/components/SoftwareTable.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEmpty: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Empty.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPagination: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USwitch: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WorkflowTable: typeof import('./src/components/WorkflowTable.vue')['default']
  }
}
