[package]
name = "glyphshift-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glyphshift-adapter-registry = { path = "../glyphshift-adapter-registry" }
glyphshift-domain = { path = "../glyphshift-domain" }
glyphshift-extension = { path = "../glyphshift-extension" }

[lints]
workspace = true
