[package]
name = "glyphshift-adapter-gdiplus-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
glyphshift-adapter-gdiplus = { path = "../glyphshift-adapter-gdiplus" }
glyphshift-adapter-native-abi = { path = "../glyphshift-adapter-native-abi" }
retour = "0.3"

[dependencies.windows]
version = "0.58"
features = ["Win32_System_LibraryLoader"]

[lints.rust]
unsafe_code = "allow"
