[package]
name = "glyphshift-adapter-direct2d-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
glyphshift-adapter-direct2d = { path = "../glyphshift-adapter-direct2d" }
glyphshift-adapter-native-abi = { path = "../glyphshift-adapter-native-abi" }
retour = "0.3"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi_Common",
]

[lints.rust]
unsafe_code = "allow"
