import { expect, test } from '@playwright/test'
import { model, storageKey } from './fixtures/productModel'

test('fallback fonts support preset and custom languages, edits, reload and removal', async ({ page }, testInfo) => {
  await page.addInitScript(({ key, value }) => localStorage.setItem(key, JSON.stringify(value)), { key: storageKey, value: model })
  await page.goto('/')
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByTestId('settings-tabs').getByRole('tab', { name: '字体', exact: true }).click()
  const section = page.getByTestId('settings-font-fallbacks')
  await section.scrollIntoViewIfNeeded()
  await section.getByRole('button', { name: '译文语言', exact: true }).click()
  await page.getByRole('option', { name: /日语.*ja/ }).click()
  await section.getByRole('button', { name: '缺字时使用', exact: true }).click()
  await page.getByRole('option', { name: 'Synthetic Sans', exact: true }).click()
  await section.getByRole('button', { name: '添加', exact: true }).click()
  await expect(section.getByRole('status')).toHaveText('已保存')
  await expect(section.getByRole('button', { name: 'ja 的备用字体', exact: true })).toContainText('Synthetic Sans')
  await section.getByRole('button', { name: '译文语言', exact: true }).click()
  await page.getByRole('combobox').filter({ visible: true }).last().fill('eo')
  await page.getByRole('option', { name: /使用语言代码.*eo/ }).click()
  await section.getByRole('button', { name: '缺字时使用', exact: true }).click()
  await page.getByRole('option', { name: 'Synthetic Serif', exact: true }).click()
  await section.getByRole('button', { name: '添加', exact: true }).click()
  await expect(section.getByRole('button', { name: 'eo 的备用字体', exact: true })).toContainText('Synthetic Serif')
  await page.reload()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByTestId('settings-tabs').getByRole('tab', { name: '字体', exact: true }).click()
  await section.scrollIntoViewIfNeeded()
  await expect(section.getByRole('button', { name: 'ja 的备用字体', exact: true })).toContainText('Synthetic Sans')
  await section.getByRole('button', { name: 'ja 的备用字体', exact: true }).click()
  await page.getByRole('option', { name: 'Synthetic Mono', exact: true }).click()
  await expect(section.getByRole('button', { name: 'ja 的备用字体', exact: true })).toContainText('Synthetic Mono')
  await section.screenshot({ path: testInfo.outputPath('font-settings-wide.png') })
  await page.setViewportSize({ width: 800, height: 680 })
  await section.scrollIntoViewIfNeeded()
  await section.screenshot({ path: testInfo.outputPath('font-settings-compact.png') })
  expect(await section.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await section.getByRole('button', { name: '移除 eo 的备用字体' }).click()
  await expect(section.getByRole('button', { name: 'eo 的备用字体', exact: true })).toHaveCount(0)
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('glyphshift.app-settings.v1')!))
  expect(saved.languageFallbackFonts).toEqual([{ language: 'ja', fontFamily: 'Synthetic Mono' }])
})
