import { expect, test } from '@playwright/test'
import { model, storageKey } from './fixtures/productModel'

const catalogModel = { ...model, software: [...model.software, { ...model.software[0], id: 'software-second', name: 'Second Studio', executableName: 'Second.exe', executablePath: 'X:\\SyntheticFixtures\\Second.exe' }] }

test.beforeEach(async ({ page }) => {
  await page.addInitScript(({ key, value }) => { if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(value)) }, { key: storageKey, value: catalogModel })
  await page.goto('/')
  await page.getByRole('button', { name: '设置', exact: true }).click()
})

test('recommended fonts add installed families without replacing favorites or restoring removed choices', async ({ page }, info) => {
  await page.evaluate(async () => {
    const path = '/src/workspace/state.ts'
    const { model } = await import(path)
    model.value.fontFamilies = ['微软雅黑', 'Microsoft YaHei', 'Arial', 'Synthetic Serif']
    const settingsPath = '/src/appSettings.ts'
    await (await import(settingsPath)).useAppSettings().setFavoriteFonts(['Synthetic Serif'])
  })
  await page.getByTestId('settings-tabs').getByRole('tab', { name: '字体管理', exact: true }).click()
  const favorites = page.getByTestId('settings-favorite-fonts')
  await favorites.getByRole('button', { name: '添加推荐字体', exact: true }).click()
  await expect(favorites.getByRole('button', { name: '取消常用字体：Synthetic Serif', exact: true })).toBeVisible()
  await expect(favorites.getByRole('button', { name: '取消常用字体：Microsoft YaHei', exact: true })).toBeVisible()
  await expect(favorites.getByRole('button', { name: '取消常用字体：微软雅黑', exact: true })).toHaveCount(0)
  await expect(favorites.getByRole('button', { name: '取消常用字体：Consolas', exact: true })).toHaveCount(0)
  await favorites.screenshot({ path: info.outputPath('recommended-fonts.png') })
  await favorites.getByRole('button', { name: '取消常用字体：Arial', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByTestId('settings-tabs').getByRole('tab', { name: '字体管理', exact: true }).click()
  await expect(favorites.getByRole('button', { name: '取消常用字体：Arial', exact: true })).toHaveCount(0)
})

test('adding a language suggests names and codes beyond the default list', async ({ page }, info) => {
  await page.getByTestId('settings-tabs').getByRole('tab', { name: '语言管理', exact: true }).click()
  const languages = page.getByTestId('settings-languages')
  const input = languages.getByRole('textbox', { name: '语言代码', exact: true })
  await input.fill('芬兰')
  await expect(languages.getByRole('button', { name: '芬兰语 · fi', exact: true })).toBeVisible()
  await languages.screenshot({ path: info.outputPath('language-suggestions.png') })
  await languages.getByRole('button', { name: '芬兰语 · fi', exact: true }).click()
  await expect(input).toHaveValue('fi')
  await languages.getByRole('button', { name: '添加语言', exact: true }).click()
  await expect(languages.getByRole('button', { name: '移除语言：fi', exact: true })).toBeVisible()
  await input.fill('x-demo')
  await languages.getByRole('button', { name: '添加语言', exact: true }).click()
  await expect(languages.getByRole('button', { name: '移除语言：x-demo', exact: true })).toBeVisible()
})

test('languages and favorite fonts persist and feed the fallback selectors', async ({ page }, info) => {
  const nav = page.getByTestId('settings-tabs')
  await nav.getByRole('tab', { name: '语言管理', exact: true }).click()
  const languages = page.getByTestId('settings-languages')
  await languages.getByRole('button', { name: '移除语言：ja', exact: true }).click()
  await languages.getByRole('textbox', { name: '语言代码', exact: true }).fill('EO')
  await languages.getByRole('button', { name: '添加语言', exact: true }).click()
  await expect(languages.getByRole('button', { name: '移除语言：eo', exact: true })).toBeVisible()
  await languages.getByRole('textbox', { name: '语言代码', exact: true }).fill('eo')
  await languages.getByRole('button', { name: '添加语言', exact: true }).click()
  await expect(languages.getByRole('alert')).toContainText('已经在列表')
  await languages.screenshot({ path: info.outputPath('languages.png') })
  await nav.getByRole('tab', { name: '字体管理', exact: true }).click()
  const favorites = page.getByTestId('settings-favorite-fonts')
  await favorites.getByRole('button', { name: '搜索本机字体', exact: true }).click()
  await page.getByRole('option', { name: 'Synthetic Serif', exact: true }).click()
  await favorites.getByRole('button', { name: '加入常用', exact: true }).click()
  await expect(favorites.getByRole('button', { name: '取消常用字体：Synthetic Serif', exact: true })).toBeVisible()
  const fallback = page.getByTestId('settings-font-fallbacks')
  await fallback.getByRole('button', { name: '译文语言', exact: true }).click()
  await expect(page.getByRole('option', { name: /日语.*ja/ })).toHaveCount(0)
  await page.getByRole('combobox').filter({ visible: true }).last().fill('eo')
  await page.getByRole('option', { name: /世界语.*eo/ }).click()
  await fallback.getByRole('button', { name: '缺字时使用', exact: true }).click()
  await expect(page.getByRole('option').first()).toHaveText('Synthetic Serif')
  await page.getByRole('option', { name: 'Synthetic Serif', exact: true }).click()
  await fallback.getByRole('button', { name: '添加', exact: true }).click()
  await expect(fallback.getByRole('button', { name: 'eo 的备用字体', exact: true })).toHaveText('Synthetic Serif')
  await page.screenshot({ path: info.outputPath('fonts-wide.png') })
  await page.reload()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await nav.getByRole('tab', { name: '语言管理', exact: true }).click()
  await expect(languages.getByRole('button', { name: '移除语言：eo', exact: true })).toBeVisible()
  await languages.getByRole('button', { name: '恢复内置语言', exact: true }).click()
  await expect(languages.getByRole('button', { name: '移除语言：eo', exact: true })).toHaveCount(0)
  await expect(languages.getByRole('button', { name: '移除语言：ja', exact: true })).toBeVisible()
  await nav.getByRole('tab', { name: '字体管理', exact: true }).click()
  await expect(fallback.getByRole('button', { name: 'eo 的备用字体', exact: true })).toHaveText('Synthetic Serif')
  await favorites.getByRole('button', { name: '取消常用字体：Synthetic Serif', exact: true }).click()
  await expect(fallback.getByRole('button', { name: 'eo 的备用字体', exact: true })).toHaveText('Synthetic Serif')
  await page.setViewportSize({ width: 800, height: 680 })
  await page.screenshot({ path: info.outputPath('fonts-compact.png') })
  expect(await favorites.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})

test('recent software can be removed and cleared without deleting software or workflow assets', async ({ page }, info) => {
  const nav = page.getByTestId('settings-tabs')
  await nav.getByRole('tab', { name: '软件管理', exact: true }).click()
  const recent = page.getByTestId('settings-recent-software')
  await expect(recent.getByText('Vector Studio', { exact: true })).toBeVisible()
  await recent.screenshot({ path: info.outputPath('recent-software.png') })
  await recent.getByRole('button', { name: '移除最近记录：Vector Studio', exact: true }).click()
  await expect(recent.getByText('Vector Studio', { exact: true })).toHaveCount(0)
  await expect(recent.getByText('Second Studio', { exact: true })).toBeVisible()
  await recent.getByRole('button', { name: '清空记录', exact: true }).click()
  await expect(recent.getByText('Second Studio', { exact: true })).toHaveCount(0)
  await page.reload()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await nav.getByRole('tab', { name: '软件管理', exact: true }).click()
  await expect(recent.getByText('Vector Studio', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('glyphshift.app-settings.v1')!).recentSoftwareIds)).toEqual([])
  const records = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), storageKey)
  expect(records.software).toHaveLength(catalogModel.software.length)
  expect(records.workflows).toEqual(model.workflows)
  await page.getByRole('navigation', { name: '主导航' }).getByRole('button', { name: '工作流', exact: true }).click()
  await page.getByRole('button', { name: '新建工作流', exact: true }).click()
  const picker = page.getByRole('dialog', { name: '设置软件', exact: true })
  await expect(picker.getByTestId('workflow-software-catalog').getByRole('button')).toHaveCount(0)
})
