import { expect, test } from '@playwright/test'
import { model, storageKey } from './fixtures/productModel'
import { selectLanguage } from './fixtures/languageSelect'

test('workflow owns per-dictionary fonts and scale and the add dialog uses managed languages', async ({ page }, info) => {
  await page.addInitScript(({ key, value }) => {
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(value))
    localStorage.setItem('glyphshift.app-settings.v1', JSON.stringify({ safetyNoticeVersion: 1, onboardingVersion: 1, favoriteFonts: ['Synthetic Serif'], translationLanguages: ['en-US', 'zh-CN', 'ja'] }))
  }, { key: storageKey, value: model })
  await page.goto('/')
  await page.getByRole('button', { name: '新建工作流', exact: true }).click()
  const software = page.getByRole('dialog', { name: '设置软件', exact: true })
  await software.getByRole('button', { name: /Vector Studio/ }).click()
  await software.getByRole('button', { name: '确认', exact: true }).click()
  await page.getByRole('tab', { name: /字典/ }).click()
  const dialog = page.getByRole('dialog', { name: '添加字典', exact: true })
  await selectLanguage(page, dialog.getByRole('button', { name: '译文语言', exact: true }), 'ja')
  await expect(dialog.getByRole('button', { name: '译文语言', exact: true })).toContainText('ja')
  await dialog.getByRole('tab', { name: '已有字典', exact: true }).click()
  await dialog.getByRole('checkbox').first().check()
  await dialog.getByRole('button', { name: '添加所选', exact: true }).click()
  const dictionariesBefore = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).dictionaries, storageKey)
  const selected = page.getByTestId('workflow-selected-dictionaries')
  await selected.getByRole('button', { name: /的字体/ }).click()
  await page.getByRole('button', { name: '常用字体', exact: true }).click()
  await expect(page.getByRole('option')).toHaveCount(1)
  await page.getByRole('option', { name: 'Synthetic Serif', exact: true }).click()
  await expect(page.getByRole('option')).toHaveCount(0)
  await selected.getByRole('spinbutton', { name: /的字号/ }).fill('125')
  await expect(selected.getByRole('spinbutton', { name: /的字号/ })).toHaveValue('125')
  await page.screenshot({ path: info.outputPath('dictionary-overrides-wide.png') })
  await page.setViewportSize({ width: 900, height: 700 })
  await page.screenshot({ path: info.outputPath('dictionary-overrides-compact.png') })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('tab', { name: /字体策略/ }).click()
  await page.getByRole('spinbutton', { name: '默认字号缩放', exact: true }).fill('150')
  await page.getByRole('tab', { name: /设置软件/ }).click()
  await page.getByTestId('workflow-adapter-config').getByRole('checkbox').nth(1).check()
  await page.getByRole('button', { name: '创建工作流', exact: true }).click()
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), storageKey)
  expect(saved.dictionaries.map((item: any) => item.metadata)).toEqual(dictionariesBefore.map((item: any) => item.metadata))
  const created = saved.workflows.find((item: any) => item.name === 'Vector Studio')
  const policy = created.targets[0].fontPolicy
  expect(policy.scalePercent).toBe(150)
  expect(Object.values(policy.dictionaryOverrides)).toEqual([{ families: ['Synthetic Serif'], scalePercent: 125 }])
  await page.reload()
  await page.getByRole('button', { name: '编辑 Vector Studio', exact: true }).click()
  await page.getByRole('tab', { name: /字典/ }).click()
  await expect(selected.getByRole('spinbutton', { name: /的字号/ })).toHaveValue('125')
  await expect(selected.getByRole('button', { name: /的字体/ })).toContainText('Synthetic Serif')
  await selected.getByRole('spinbutton', { name: /的字号/ }).fill('')
  await page.getByRole('button', { name: '保存工作流', exact: true }).click()
  const updated = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), storageKey)
  const override = Object.values(updated.workflows.find((item: any) => item.id === created.id).targets[0].fontPolicy.dictionaryOverrides)[0]
  expect(override).toEqual({ families: ['Synthetic Serif'], scalePercent: null })

})

test('about links open the supplied documentation and release pages', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => { (window as any).__openedLinks = []; window.open = ((url: string) => { (window as any).__openedLinks.push(url); return null }) as typeof window.open })
  await page.getByRole('button', { name: '帮助', exact: true }).click()
  await page.getByRole('tab', { name: '关于', exact: true }).click()
  await page.getByRole('button', { name: '打开在线文档', exact: true }).click()
  await page.getByRole('button', { name: '打开软件发布页面', exact: true }).click()
  expect(await page.evaluate(() => (window as any).__openedLinks)).toEqual(['https://docs.yuelili.com/glyphshift', 'https://www.yuelili.com/apps/glyphshift'])
})
