[package]
name = "glyphshift-resource-inspector"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
glyphshift-dictionary-package = { path = "../package" }
glyphshift-plugin-package = { path = "../../adapters/platform/package" }
serde_json = "1.0"

[lints]
workspace = true
