[package]
name = "glyphshift-adapter-console-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
glyphshift-adapter-console = { path = "../glyphshift-adapter-console" }
glyphshift-adapter-native-abi = { path = "../glyphshift-adapter-native-abi" }
retour = "0.3"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
]

[lints.rust]
unsafe_code = "allow"
