[package]
name = "glyphshift-dictionary-package"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
glyphshift-translation = { path = "../../core/translation" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints]
workspace = true
